/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : filterTimer.h
**     Project     : ProcessorExpert
**     Processor   : MC9S08JM60CLHE
**     Component   : TimerOut
**     Version     : Component 03.030, Driver 01.24, CPU db: 3.00.050
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2013-07-24, 14:08, # CodeGen: 79
**     Abstract    :
**         This component implements a periodic signal generator 1:1 (Flip-Flop Output).
**         The signal alternates the "0" and "1" output values in exactly
**         regular intervals; that is why the time length of the "0" part
**         of one pulse is equal to the "1" part of one pulse.
**     Settings    :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       8             |  PTF4_TPM2CH0
**             ----------------------------------------------------
**
**         Timer name                  : TPM2 (16-bit)
**         Compare name                : TPM20
**           Counter shared            : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 24000000 Hz
**           Pulse width
**             Xtal ticks              : 200
**             microseconds            : 17
**             seconds (real)          : 0.000016666667
**             Hz                      : 60000
**             kHz                     : 60
**
**         Runtime setting             : none
**
**         Initialization:
**              Output level           : low
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TPM2CNT   [$0061]
**              Mode                   : TPM2SC    [$0060]
**              Run                    : TPM2SC    [$0060]
**              Prescaler              : TPM2SC    [$0060]
**
**         Compare registers
**              Compare                : TPM2C0V   [$0066]
**
**         Flip-flop registers
**              Mode                   : TPM2C0SC  [$0065]
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file filterTimer.h
** @version 01.24
** @brief
**         This component implements a periodic signal generator 1:1 (Flip-Flop Output).
**         The signal alternates the "0" and "1" output values in exactly
**         regular intervals; that is why the time length of the "0" part
**         of one pulse is equal to the "1" part of one pulse.
*/         
/*!
**  @addtogroup filterTimer_module filterTimer module documentation
**  @{
*/         

#ifndef __filterTimer
#define __filterTimer

/* MODULE filterTimer. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

void filterTimer_InitTO(void);
/*
** ===================================================================
**     Method      :  filterTimer_InitTO (component TimerOut)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define filterTimer_SetCV(_Val) { \
  TPM2C0V = (word)(_Val); \
  TPM2MOD = (word)(_Val); \
}
/*
** ===================================================================
**     Method      :  SetCV (component TimerOut)
**
**     Description :
**         The method computes and sets compare eventually modulo value 
**         for time measuring.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END filterTimer. */

#endif /* ifndef __filterTimer */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.07]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
