/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : massStorageSerial.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08JM60CLDE
**     Component   : AsynchroMaster
**     Version     : Component 02.288, Driver 01.33, CPU db: 3.00.048
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2013-05-27, 12:03, # CodeGen: 7
**     Abstract    :
**         This component "AsynchroMaster" implements MASTER part of asynchronous
**         serial master-slave communication.
**     Settings    :
**         Asynchro type               : MASTER
**
**         Serial channel              : SCI2
**
**         Protocol
**             Init baud rate          : 375000baud
**             Width                   : 9 bits
**             Stop bits               : 0
**             Parity                  : hardware wake-up
**             Breaks                  : Disabled
**             Input buffer size       : 0
**             Output buffer size      : 0
**
**         Registers
**             Input buffer            : SCI2D     [$0047]
**             Output buffer           : SCI2D     [$0047]
**             Control register        : SCI2C1    [$0042]
**             Mode register           : SCI2C2    [$0043]
**             Baud setting reg.       : SCI2BD    [$0040]
**             Special register        : SCI2S1    [$0044]
**
**
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     44               |  PTC5_RxD2
**            Output  |     43               |  PTC3_TxD2
**         ----------------------------------------------------------
**
**     Contents    :
**         RecvChar        - byte massStorageSerial_RecvChar(massStorageSerial_TComData *Chr);
**         SendChar        - byte massStorageSerial_SendChar(massStorageSerial_TComData Chr);
**         GetCharsInRxBuf - word massStorageSerial_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word massStorageSerial_GetCharsInTxBuf(void);
**         SelectSlave     - byte massStorageSerial_SelectSlave(byte Slv);
**         GetSelected     - byte massStorageSerial_GetSelected(byte *Slv);
**         SetIdle         - byte massStorageSerial_SetIdle(void);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE massStorageSerial. */

#pragma MESSAGE DISABLE C4002 /* WARNING C4002: Result not used is ignored */

#include "massStorageSerial.h"



static byte SerSlv;                    /* Number of selected slave mode */
/*
** ===================================================================
**     Method      :  massStorageSerial_RecvChar (component AsynchroMaster)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). This method is enabled only if the receiver property
**         is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence the
**         information about an exception in interrupt mode is returned
**         only if there is a valid character ready to be read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service> property
**                           is disabled and the <Break signal> property
**                           is enabled)
**                           ERR_COMMON - common error occurred (the
**                           GetError method can be used for error
**                           specification)
** ===================================================================
*/
byte massStorageSerial_RecvChar(massStorageSerial_TComData *Chr)
{
  byte Result = ERR_OK;                /* Prepare default error code */
  byte StatReg = SCI2S1;               /* Read status register */

  (void)SCI2C3;                        /* Dummy read of SCIxC3, reading of R8 bit */
  if (StatReg & (SCI2S1_OR_MASK|SCI2S1_NF_MASK|SCI2S1_FE_MASK)) { /* Is any error set? */
    Result = ERR_COMMON;               /* If yes then set common error value */
  } else if ((StatReg & SCI2S1_RDRF_MASK) == 0U) { /* Is the reciver empty and no error is set? */
    return ERR_RXEMPTY;                /* If yes then error */
  } else {                             /* Intentionally left empty due to compatibility with MISRA rule 60*/
  }
  *Chr = SCI2D;                        /* Read data from the receiver */
  return Result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  massStorageSerial_SendChar (component AsynchroMaster)
**
**     Description :
**         Send one character to the channel. This method is available
**         only if the transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte massStorageSerial_SendChar(massStorageSerial_TComData Chr)
{
  if (SCI2S1_TDRE == 0U) {             /* Is the transmitter full? */
    return ERR_TXFULL;                 /* If yes then error */
  }
  SCI2C3_T8 = 0U;                      /* Set the ninth bit */
  SCI2D = (byte)Chr;                   /* Store char to transmitter register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  massStorageSerial_GetCharsInRxBuf (component AsynchroMaster)
**
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the input
**                           buffer.
** ===================================================================
*/
/*
word massStorageSerial_GetCharsInRxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  massStorageSerial_GetCharsInTxBuf (component AsynchroMaster)
**
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the output
**                           buffer.
** ===================================================================
*/
/*
word massStorageSerial_GetCharsInTxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  massStorageSerial_Init (component AsynchroMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void massStorageSerial_Init(void)
{
  SerSlv = (byte) NOSLAVE;             /* No slave is selected */
  /* SCI2C1: LOOPS=0,SCISWAI=0,RSRC=0,M=1,WAKE=0,ILT=0,PE=0,PT=0 */
  setReg8(SCI2C1, 0x10U);              /* Configure the SCI */ 
  /* SCI2C3: R8=0,T8=0,TXDIR=0,TXINV=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
  setReg8(SCI2C3, 0x00U);              /* Disable error interrupts */ 
  /* SCI2C2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  setReg8(SCI2C2, 0x00U);              /* Disable all interrupts */ 
  /* SCI2S2: LBKDIF=0,RXEDGIF=0,??=0,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
  setReg8(SCI2S2, 0x00U);               
  SCI2BDH = 0x00U;                     /* Set high divisor register (enable device) */
  SCI2BDL = 0x01U;                     /* Set low divisor register (enable device) */
  SCI2C2_TE = 0x01U;                    /* Enable transmitter */
  SCI2C2_RE = 0x01U;                    /* Enable receiver */
}

/*
** ===================================================================
**     Method      :  massStorageSerial_SetIdle (component AsynchroMaster)
**
**     Description :
**         Sends the idle character to the output line.
**         This method is available only if the transmitter property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This component is disabled
**                           by user
** ===================================================================
*/
byte massStorageSerial_SetIdle(void)
{
  SCI2C2_TE = 0x00U;                   /* Disable the transmitter */
  SCI2C2_TE = 0x01U;                   /* Enable the transmitter */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  massStorageSerial_SelectSlave (component AsynchroMaster)
**
**     Description :
**         Select the slave - sends the address of the slave for
**         starting communication with it (the previous slave stops
**         communicating).
**     Parameters  :
**         NAME            - DESCRIPTION
**         Slv             - The new slave identification
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This device is disabled
**                           ERR_BUSY - Transmitter buffer is not empty
** ===================================================================
*/
byte massStorageSerial_SelectSlave(byte Slv)
{
  if (SCI2S1_TDRE == 0U) {             /* Is the transmitter empty? */
    return ERR_BUSY;                   /* If no then return error */
  }
  SerSlv = Slv;                        /* Save identification of the selected slave */
  (void)SCI2S1;                        /* Reset interrupt request flag */
  SCI2C3_T8 = 1U;                      /* Set the ninth bit to 1 */
  SCI2D = Slv;                         /* Store slave address to the transmitter register */
  while(SCI2S1_TDRE == 0U) {}          /* Wait until the char is not out from the transmitter */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  massStorageSerial_GetSelected (component AsynchroMaster)
**
**     Description :
**         Return the identification of the selected slave  (0-254, or
**         -1 if no slave is selected).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Slv             - Pointer to identification of the slave
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Slave is not selected yet
** ===================================================================
*/
byte massStorageSerial_GetSelected(byte *Slv)
{
  if (SerSlv == (byte)NOSLAVE) {       /* Is any slave selected? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *Slv = SerSlv;                       /* Return address of the selected slave */
  return ERR_OK;                       /* OK */
}


/* END massStorageSerial. */


/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
