/*
** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PE_Cnvrt.inc
**     Project     : ProcessorExpert
**     Processor   : MC9S08JM60CLDE
**     Component   : PE_Cnvrt
**     Version     : Driver 01.17
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2013-05-23, 16:46, # CodeGen: 6
**     Abstract    :
**         This component "PE_Cnvrt" implements internal methods and definitions
**         used by components working with converters.
**     Settings    :
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

#ifndef __PE_Cnvrt
#define __PE_Cnvrt

/* MODULE PE_Cnvrt. */
#include "PE_Types.h"


/* Internal method prototypes */

void PE_Cnvrt_InterruptInternal(void);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_InterruptInternal (component PE_Cnvrt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         .
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

typedef void (*TProc)(void);

typedef byte PE_Cnvrt_ChanMaskType;    /* Type used to define channel mask */

void PE_Cnvrt_Init(void);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_PE_CnvrtPE_Init (component PE_Cnvrt)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void PE_Cnvrt_Interrupt(void);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_PE_CnvrtInterrupt (component PE_Cnvrt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         .
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_SetSpe(byte Index, byte NewSpe);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_SetSpe (component PE_Cnvrt)
**
**     Description :
**         The method stores the configuration of the AD converter for 
**         the specified channel.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_SetPro(byte Index, TProc Proc);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_SetPro (component PE_Cnvrt)
**
**     Description :
**         The method stores the pointer to the service routine for 
**         specified channel.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_RunSta(PE_Cnvrt_ChanMaskType Mask);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_RunSta (component PE_Cnvrt)
**
**     Description :
**         The method enables measurement of channels given by a mask.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_RunSto(PE_Cnvrt_ChanMaskType Mask);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_RunSto (component PE_Cnvrt)
**
**     Description :
**         The method disables measurement of channels given by a mask.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END PE_Cnvrt. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
#endif /* ifndef __PE_Cnvrt */
