/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : receiveLED.h
**     Project     : ProcessorExpert
**     Processor   : MC9S08JM60CLDE
**     Component   : BitIO
**     Version     : Component 02.086, Driver 03.27, CPU db: 3.00.048
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2013-05-27, 12:03, # CodeGen: 7
**     Abstract    :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings    :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       5             |  PTF1_TPM1CH3
**             ----------------------------------------------------
**
**         Port name                   : PTF
**
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : off
**
**         Port data register          : PTFD      [$000A]
**         Port control register       : PTFDD     [$000B]
**
**         Optimization for            : speed
**     Contents    :
**         GetVal - bool receiveLED_GetVal(void);
**         PutVal - void receiveLED_PutVal(bool Val);
**         ClrVal - void receiveLED_ClrVal(void);
**         SetVal - void receiveLED_SetVal(void);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef receiveLED_H_
#define receiveLED_H_

/* MODULE receiveLED. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  receiveLED_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define receiveLED_GetVal() ( \
    (bool)((getReg8(PTFD) & 0x02U))    /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  receiveLED_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void receiveLED_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  receiveLED_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define receiveLED_ClrVal() ( \
    (void)clrReg8Bits(PTFD, 0x02U)     /* PTFD1=0x00U */ \
  )

/*
** ===================================================================
**     Method      :  receiveLED_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define receiveLED_SetVal() ( \
    (void)setReg8Bits(PTFD, 0x02U)     /* PTFD1=0x01U */ \
  )



/* END receiveLED. */
#endif /* #ifndef __receiveLED_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
