/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : wirelessSerial.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08JM60CLDE
**     Component   : SynchroMaster
**     Version     : Component 02.345, Driver 01.30, CPU db: 3.00.048
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2013-05-27, 12:03, # CodeGen: 7
**     Abstract    :
**         This component "SynchroMaster" implements MASTER part of synchronous
**         serial master-slave communication.
**     Settings    :
**         Synchro type                : MASTER
**
**         Serial channel              : SPI1
**
**         Protocol
**             Init baud rate          : 0_333333us
**             Clock edge              : rising
**             Width                   : 8 bits
**             Empty character         : 0
**             Empty char. on input    : RECEIVED
**
**         Registers
**             Input buffer            : SPI1DL    [$0055]
**             Output buffer           : SPI1DL    [$0055]
**             Control register        : SPI1C1    [$0050]
**             Mode register           : SPI1C2    [$0051]
**             Baud setting reg.       : SPI1BR    [$0052]
**
**             Priority                : 
**
**             Priority                : 
**
**         Used pins                   :
**         ----------------------------------------------------------
**              Function    | On package |    Name
**         ----------------------------------------------------------
**               Input      |     12     |  PTE4_MISO1
**               Output     |     13     |  PTE5_MOSI1
**               Clock      |     14     |  PTE6_SPSCK1
**         ----------------------------------------------------------
**
**     Contents    :
**         RecvChar        - byte wirelessSerial_RecvChar(wirelessSerial_TComData *Chr);
**         SendChar        - byte wirelessSerial_SendChar(wirelessSerial_TComData Chr);
**         GetCharsInRxBuf - word wirelessSerial_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word wirelessSerial_GetCharsInTxBuf(void);
**         GetError        - byte wirelessSerial_GetError(wirelessSerial_TError *Err);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE wirelessSerial. */

#include "wirelessSerial.h"
#include "massStorageSerial.h"
#include "powerLED.h"
#include "statusLED.h"
#include "transmitLED.h"
#include "receiveLED.h"
#include "accelerometer.h"
#include "batteryMonitor.h"
#include "samplingTimer.h"
#include "Events.h"


/* Internal method prototypes */

#define OVERRUN_ERR      0x01U         /* Overrun error flag bit   */
#define CHAR_IN_RX       0x08U         /* Char is in RX buffer     */
#define FULL_TX          0x10U         /* Full transmit buffer     */
#define RUNINT_FROM_TX   0x20U         /* Interrupt is in progress */
#define FULL_RX          0x40U         /* Full receive buffer      */

static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Unused */
                                       /*       2 - Unused */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Unused */
static byte ErrFlag;                   /* Error flags mirror of SerFlag */
static wirelessSerial_TComData BufferRead; /* Input char SPI commmunication */

/*
** ===================================================================
**     Method      :  wirelessSerial_RecvChar (component SynchroMaster)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). 
**         For information about SW overrun behavior please see
**         <General info page>.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK - The valid data is received.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode.
**                           ERR_RXEMPTY - No data in receiver.
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last char or block received. In
**                           polling mode, this error code is returned
**                           only when the hardware supports detection
**                           of the overrun error. If interrupt service
**                           is enabled, and input buffer allocated by
**                           the component is full, the component
**                           behaviour depends on <Input buffer size>
**                           property : if property is 0, last received
**                           data-word is preserved (and previous is
**                           overwritten), if property is greater than 0,
**                           new received data-word are ignored.
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. In the
**                           polling mode the ERR_FAULT is return until
**                           the user clear the fault flag bit, but in
**                           the interrupt mode ERR_FAULT is returned
**                           only once after the fault error occured.
**                           This error is supported only on the CPUs
**                           supports the faul mode function - where
**                           <Fault mode> property is available.
** ===================================================================
*/
byte wirelessSerial_RecvChar(wirelessSerial_TComData *Chr)
{
  byte FlagTmp;

  if ((SerFlag & CHAR_IN_RX) == 0U) {  /* Is any char in RX buffer? */
    return ERR_RXEMPTY;                /* If no then error */
  }
  EnterCritical();                     /* Save the PS register */
  *Chr = BufferRead;                   /* Read the char */
  FlagTmp = SerFlag;                   /* Safe the flags */
  SerFlag &= (byte)(~(byte)(OVERRUN_ERR | CHAR_IN_RX | FULL_RX)); /* Clear flag "char in RX buffer" */
  ExitCritical();                      /* Restore the PS register */
  if ((FlagTmp & OVERRUN_ERR) != 0U) { /* Has the overrun occurred? */
    return ERR_OVERRUN;                /* If yes then return error */
  } else {
    return ERR_OK;
  }
}

/*
** ===================================================================
**     Method      :  wirelessSerial_SendChar (component SynchroMaster)
**
**     Description :
**         Sends one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte wirelessSerial_SendChar(wirelessSerial_TComData Chr)
{
  if (SerFlag & FULL_TX) {             /* Is any char in the TX buffer? */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Save the PS register */
  (void)SPI1S;                         /* Read the status register */
  SPI1DL = Chr;                        /* Store char to transmitter register */
  SerFlag |= FULL_TX;                  /* Set the flag "full TX buffer" */
  ExitCritical();                      /* Restore the PS register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  wirelessSerial_GetCharsInRxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input buffer.
** ===================================================================
*/
word wirelessSerial_GetCharsInRxBuf(void)
{
  return (word)((SerFlag & CHAR_IN_RX) ? (word)1U : (word)0U); /* Return number of chars in the receive buffer */
}
/*
** ===================================================================
**     Method      :  wirelessSerial_GetCharsInTxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the output buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output buffer.
** ===================================================================
*/
word wirelessSerial_GetCharsInTxBuf(void)
{
  return (word)((SerFlag & FULL_TX) ? (word)1U : (word)0U); /* Return number of chars in the transmit buffer */
}
/*
** ===================================================================
**     Method      :  wirelessSerial_GetError (component SynchroMaster)
**
**     Description :
**         Returns a set of errors on the channel (errors that cannot
**         be returned in given methods). The component accumulates
**         errors in a set; after calling [GetError] this set is
**         returned and cleared. This method is available only if the
**         "Interrupt service/event" property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - A pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte wirelessSerial_GetError(wirelessSerial_TError *Err)
{
  EnterCritical();                     /* Save the PS register */
  Err->err = 0x00U;
  Err->errName.OverRun = ((ErrFlag & OVERRUN_ERR) ? 1U : 0U); /* Overrun error */
  ErrFlag = 0x00U;                     /* Reset error flags */
  ExitCritical();                      /* Restore the PS register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  wirelessSerial_Interrupt (component SynchroMaster)
**
**     Description :
**         The method services the error interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR       0x01U
#define ON_FULL_RX     0x02U
#define ON_RX_CHAR     0x04U
#define ON_FREE_TX     0x08U
#define ON_TX_CHAR     0x10U
#define ON_RX_CHAR_EXT 0x20U
ISR(wirelessSerial_Interrupt)
{
  wirelessSerial_TComData Data = 0U;   /* Temporary variable for data */
  byte Flags = 0U;                     /* Temporary variable for flags */
  byte Status;                         /* Temporary variable for flags */

  Status = SPI1S;                      /* Read the device error register */
  Data = SPI1DL;                       /* Read data from receiver */
  if (SerFlag & CHAR_IN_RX) {          /* Is the overrun error flag set? */
    SerFlag |= OVERRUN_ERR;            /* If yes then set the Overrun error flag */
    Flags |= ON_ERROR;                 /* If yes then set the OnError flag */
  }
  SerFlag |= CHAR_IN_RX;               /* Set flag "char in RX buffer" */
  BufferRead = Data;                   /* Read data from receiver */
  Flags |= ON_RX_CHAR;                 /* Set the OnRxChar flag */
  ErrFlag |= SerFlag;                  /* Update error flag mirror */
  SerFlag &= (byte)(~(byte)FULL_TX);   /* Reset flag "full TX buffer" */

  if (Flags & ON_ERROR) {              /* Is the error flag set? */
    wirelessSerial_OnError();          /* If yes then invoke user event */
  } else {
    if (Flags & ON_RX_CHAR) {          /* Is OnRxChar flag set? */
      wirelessSerial_OnRxChar();       /* If yes then invoke user event */
    }
  }
  wirelessSerial_OnTxChar();           /* If yes then invoke user event */
}

/*
** ===================================================================
**     Method      :  wirelessSerial_Init (component SynchroMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void wirelessSerial_Init(void)
{
  SerFlag = 0U;                        /* Reset all flags */
  ErrFlag = 0U;                        /* Reset all flags in mirror */
  #pragma MESSAGE DISABLE C4002        /* Disable warning C4002 "Result not used" */
  (void)SPI1S;                         /* Read the status register */
  (void)SPI1DL;                        /* Read the data register */
  /* SPI1BR: ??=0,SPPR2=0,SPPR1=0,SPPR0=0,??=0,SPR2=0,SPR1=0,SPR0=0 */
  setReg8(SPI1BR, 0x00U);              /* Set the baud rate register */ 
  /* SPI1C2: SPMIE=0,SPIMODE=0,??=0,MODFEN=0,BIDIROE=0,??=0,SPISWAI=0,SPC0=0 */
  setReg8(SPI1C2, 0x00U);              /* Configure the SPI port - control register 2 */ 
  /* SPI1C1: SPIE=1,SPE=0,SPTIE=0,MSTR=1,CPOL=0,CPHA=1,SSOE=0,LSBFE=1 */
  setReg8(SPI1C1, 0x95U);              /* Configure the SPI port - control register 1 */ 
  SPI1C1_SPE = 1U;                     /* Enable device */
}


/* END wirelessSerial. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
