/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : wirelessSerial.h
**     Project     : ProcessorExpert
**     Processor   : MC9S08JM60CLDE
**     Component   : SynchroMaster
**     Version     : Component 02.345, Driver 01.30, CPU db: 3.00.048
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2013-05-27, 12:03, # CodeGen: 7
**     Abstract    :
**         This component "SynchroMaster" implements MASTER part of synchronous
**         serial master-slave communication.
**     Settings    :
**         Synchro type                : MASTER
**
**         Serial channel              : SPI1
**
**         Protocol
**             Init baud rate          : 0_333333us
**             Clock edge              : rising
**             Width                   : 8 bits
**             Empty character         : 0
**             Empty char. on input    : RECEIVED
**
**         Registers
**             Input buffer            : SPI1DL    [$0055]
**             Output buffer           : SPI1DL    [$0055]
**             Control register        : SPI1C1    [$0050]
**             Mode register           : SPI1C2    [$0051]
**             Baud setting reg.       : SPI1BR    [$0052]
**
**             Priority                : 
**
**             Priority                : 
**
**         Used pins                   :
**         ----------------------------------------------------------
**              Function    | On package |    Name
**         ----------------------------------------------------------
**               Input      |     12     |  PTE4_MISO1
**               Output     |     13     |  PTE5_MOSI1
**               Clock      |     14     |  PTE6_SPSCK1
**         ----------------------------------------------------------
**
**     Contents    :
**         RecvChar        - byte wirelessSerial_RecvChar(wirelessSerial_TComData *Chr);
**         SendChar        - byte wirelessSerial_SendChar(wirelessSerial_TComData Chr);
**         GetCharsInRxBuf - word wirelessSerial_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word wirelessSerial_GetCharsInTxBuf(void);
**         GetError        - byte wirelessSerial_GetError(wirelessSerial_TError *Err);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __wirelessSerial
#define __wirelessSerial

/* MODULE wirelessSerial. */

#include "Cpu.h"



#define wirelessSerial_EOF 0x00U       /* Value of the empty character defined in the Empty character property. */

#ifndef __BWUserType_wirelessSerial_TComData
#define __BWUserType_wirelessSerial_TComData
  typedef byte wirelessSerial_TComData; /* User type for communication. */
#endif

#ifndef __BWUserType_wirelessSerial_TError
#define __BWUserType_wirelessSerial_TError
  /*lint -save  -esym(960,18.4) Disable MISRA rule (18.4) checking. */
  typedef union {
    byte err;
    struct {
      /*lint -save  -e46 Disable MISRA rule (6.4) checking. */
      bool OverRun  : 1;   /* OverRun error flag - the data overflow on the input has been detected. Both hardware detection (if supported) and software detection (when the value of Input buffer size property is 0) is used. */
      bool RxBufOvf : 1;   /* Rx buffer full error flag - the input circular buffer defined by the Input buffer size property has overrun. */
      bool FaultErr : 1;   /* Fault mode error flag - only if supported by hardware */
      /*lint -restore Enable MISRA rule (6.4) checking. */
    }errName;
  } wirelessSerial_TError;             /* Error flags. For languages which don't support bit access is byte access only to error flags possible.  */
  /*lint -restore  +esym(960,18.4) Enable MISRA rule (18.4) checking. */
#endif




byte wirelessSerial_RecvChar(wirelessSerial_TComData *Chr);
/*
** ===================================================================
**     Method      :  wirelessSerial_RecvChar (component SynchroMaster)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). 
**         For information about SW overrun behavior please see
**         <General info page>.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK - The valid data is received.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode.
**                           ERR_RXEMPTY - No data in receiver.
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last char or block received. In
**                           polling mode, this error code is returned
**                           only when the hardware supports detection
**                           of the overrun error. If interrupt service
**                           is enabled, and input buffer allocated by
**                           the component is full, the component
**                           behaviour depends on <Input buffer size>
**                           property : if property is 0, last received
**                           data-word is preserved (and previous is
**                           overwritten), if property is greater than 0,
**                           new received data-word are ignored.
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. In the
**                           polling mode the ERR_FAULT is return until
**                           the user clear the fault flag bit, but in
**                           the interrupt mode ERR_FAULT is returned
**                           only once after the fault error occured.
**                           This error is supported only on the CPUs
**                           supports the faul mode function - where
**                           <Fault mode> property is available.
** ===================================================================
*/

byte wirelessSerial_SendChar(wirelessSerial_TComData Chr);
/*
** ===================================================================
**     Method      :  wirelessSerial_SendChar (component SynchroMaster)
**
**     Description :
**         Sends one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/

word wirelessSerial_GetCharsInRxBuf(void);
/*
** ===================================================================
**     Method      :  wirelessSerial_GetCharsInRxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input buffer.
** ===================================================================
*/

word wirelessSerial_GetCharsInTxBuf(void);
/*
** ===================================================================
**     Method      :  wirelessSerial_GetCharsInTxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the output buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output buffer.
** ===================================================================
*/

byte wirelessSerial_GetError(wirelessSerial_TError *Err);
/*
** ===================================================================
**     Method      :  wirelessSerial_GetError (component SynchroMaster)
**
**     Description :
**         Returns a set of errors on the channel (errors that cannot
**         be returned in given methods). The component accumulates
**         errors in a set; after calling [GetError] this set is
**         returned and cleared. This method is available only if the
**         "Interrupt service/event" property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - A pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

__interrupt void wirelessSerial_Interrupt(void);
/*
** ===================================================================
**     Method      :  wirelessSerial_Interrupt (component SynchroMaster)
**
**     Description :
**         The method services the error interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void wirelessSerial_Init(void);
/*
** ===================================================================
**     Method      :  wirelessSerial_Init (component SynchroMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END wirelessSerial. */

#endif /* ifndef __wirelessSerial */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
