/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SDSerial.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08JM60CLHE
**     Component   : SynchroMaster
**     Version     : Component 02.345, Driver 01.30, CPU db: 3.00.050
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2013-07-19, 01:33, # CodeGen: 58
**     Abstract    :
**         This component "SynchroMaster" implements MASTER part of synchronous
**         serial master-slave communication.
**     Settings    :
**         Synchro type                : MASTER
**
**         Serial channel              : SPI2
**
**         Protocol
**             Init baud rate          : 2_666667us
**             Clock edge              : rising
**             Width                   : 8 bits
**             Empty character         : 0
**             Empty char. on input    : RECEIVED
**
**         Registers
**             Input buffer            : SPI2DL    [$0075]
**             Output buffer           : SPI2DL    [$0075]
**             Control register        : SPI2C1    [$0070]
**             Mode register           : SPI2C2    [$0071]
**             Baud setting reg.       : SPI2BR    [$0072]
**
**             Priority                : 
**
**             Priority                : 
**
**         Used pins                   :
**         ----------------------------------------------------------
**              Function    | On package |    Name
**         ----------------------------------------------------------
**               Input      |     34     |  PTB0_MISO2_ADP0
**               Output     |     35     |  PTB1_MOSI2_ADP1
**               Clock      |     36     |  PTB2_SPSCK2_ADP2
**         ----------------------------------------------------------
**
**         Used baud modes:
**         ----------------------------------------------------------
**           No.     |    Mode ID            |  Baud rate
**         ----------------------------------------------------------
**            0      |  SDSerial_BM_2_666667US      |  2_666667us
**            1      |  SDSerial_BM_0_083333US      |  0_083333us
**         ----------------------------------------------------------
**     Contents    :
**         Enable          - byte SDSerial_Enable(void);
**         Disable         - byte SDSerial_Disable(void);
**         RecvChar        - byte SDSerial_RecvChar(SDSerial_TComData *Chr);
**         SendChar        - byte SDSerial_SendChar(SDSerial_TComData Chr);
**         GetCharsInRxBuf - word SDSerial_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word SDSerial_GetCharsInTxBuf(void);
**         SetBaudRateMode - byte SDSerial_SetBaudRateMode(byte Mod);
**         GetError        - byte SDSerial_GetError(SDSerial_TError *Err);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file SDSerial.c
** @version 01.30
** @brief
**         This component "SynchroMaster" implements MASTER part of synchronous
**         serial master-slave communication.
*/         
/*!
**  @addtogroup SDSerial_module SDSerial module documentation
**  @{
*/         


/* MODULE SDSerial. */

#include "SDSerial.h"
#include "AD1.h"
#include "sampleTimer.h"
#include "filterTimer.h"
#include "Events.h"


/* Internal method prototypes */
static void HWEnDi(void);

#define OVERRUN_ERR      0x01U         /* Overrun error flag bit   */
#define CHAR_IN_RX       0x08U         /* Char is in RX buffer     */
#define FULL_TX          0x10U         /* Full transmit buffer     */
#define RUNINT_FROM_TX   0x20U         /* Interrupt is in progress */
#define FULL_RX          0x40U         /* Full receive buffer      */

static bool EnUser;                    /* Enable/Disable SPI */
static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Unused */
                                       /*       2 - Unused */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Unused */
static byte ErrFlag;                   /* Error flags mirror of SerFlag */
static SDSerial_TComData BufferRead;   /* Input char SPI commmunication */
static SDSerial_TComData BufferWrite;  /* Output char SPI commmunication */

/*
** ===================================================================
**     Method      :  HWEnDi (component SynchroMaster)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    SPI2C1_SPE = 1U;                   /* Enable device */
    SPI2C1_SPIE = 1U;                  /* Enable interrupts */
    if (SerFlag & FULL_TX) {           /* Is there any char in the transmit buffer? */
      (void)SPI2S;                     /* Read the status register */
      SPI2DL = BufferWrite;            /* Store char to the transmit register */
    }
  } else {
    SPI2C1_SPE = 0U;                   /* Disable device */
    SPI2C1_SPIE = 0U;                  /* Disable interrupts */
  }
}

/*
** ===================================================================
**     Method      :  SDSerial_Enable (component SynchroMaster)
**     Description :
**         Enable the component - it starts send and receive functions.
**         Events may be generated ("DisableEvent"/"EnableEvent"). This
**         method cannot be disabled if the Fault mode is enabled. It's
**         intended for re-enabling the module if fault occurred. For
**         more information please see the <"Fault mode" >property .
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SDSerial_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SDSerial_Disable (component SynchroMaster)
**     Description :
**         Disable the component - it stops the send and receive
**         functions. No events will be generated. Note: When this
**         method is called while a transmission is in progress, the
**         data being transmitted/received may be lost.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SDSerial_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SDSerial_RecvChar (component SynchroMaster)
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). 
**         For information about SW overrun behavior please see
**         <General info page>.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK - The valid data is received.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode.
**                           ERR_RXEMPTY - No data in receiver.
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last char or block received. In
**                           polling mode, this error code is returned
**                           only when the hardware supports detection
**                           of the overrun error. If interrupt service
**                           is enabled, and input buffer allocated by
**                           the component is full, the component
**                           behaviour depends on <Input buffer size>
**                           property : if property is 0, last received
**                           data-word is preserved (and previous is
**                           overwritten), if property is greater than 0,
**                           new received data-word are ignored.
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. In the
**                           polling mode the ERR_FAULT is return until
**                           the user clear the fault flag bit, but in
**                           the interrupt mode ERR_FAULT is returned
**                           only once after the fault error occured.
**                           This error is supported only on the CPUs
**                           supports the faul mode function - where
**                           <Fault mode> property is available.
** ===================================================================
*/
byte SDSerial_RecvChar(SDSerial_TComData *Chr)
{
  byte FlagTmp;

  if ((SerFlag & CHAR_IN_RX) == 0U) {  /* Is any char in RX buffer? */
    return ERR_RXEMPTY;                /* If no then error */
  }
  EnterCritical();                     /* Save the PS register */
  *Chr = BufferRead;                   /* Read the char */
  FlagTmp = SerFlag;                   /* Safe the flags */
  SerFlag &= (byte)(~(byte)(OVERRUN_ERR | CHAR_IN_RX | FULL_RX)); /* Clear flag "char in RX buffer" */
  ExitCritical();                      /* Restore the PS register */
  if ((FlagTmp & OVERRUN_ERR) != 0U) { /* Has the overrun occurred? */
    return ERR_OVERRUN;                /* If yes then return error */
  } else {
    return ERR_OK;
  }
}

/*
** ===================================================================
**     Method      :  SDSerial_SendChar (component SynchroMaster)
**     Description :
**         Sends one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte SDSerial_SendChar(SDSerial_TComData Chr)
{
  if (SerFlag & FULL_TX) {             /* Is any char in the TX buffer? */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Save the PS register */
  BufferWrite = Chr;                   /* Store char to the temporary variable */
  if(EnUser) {                         /* Is the device enabled by user? */
    (void)SPI2S;                       /* Read the status register */
    SPI2DL = Chr;                      /* Store char to transmitter register */
  }
  SerFlag |= FULL_TX;                  /* Set the flag "full TX buffer" */
  ExitCritical();                      /* Restore the PS register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SDSerial_GetCharsInRxBuf (component SynchroMaster)
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input buffer.
** ===================================================================
*/
word SDSerial_GetCharsInRxBuf(void)
{
  return (word)((SerFlag & CHAR_IN_RX) ? (word)1U : (word)0U); /* Return number of chars in the receive buffer */
}
/*
** ===================================================================
**     Method      :  SDSerial_GetCharsInTxBuf (component SynchroMaster)
**     Description :
**         Returns the number of characters in the output buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output buffer.
** ===================================================================
*/
word SDSerial_GetCharsInTxBuf(void)
{
  return (word)((SerFlag & FULL_TX) ? (word)1U : (word)0U); /* Return number of chars in the transmit buffer */
}
/*
** ===================================================================
**     Method      :  SDSerial_SetBaudRateMode (component SynchroMaster)
**     Description :
**         This method changes the channel communication speed (baud
**         rate). This method can be used only if you specify a list
**         of possible period settings at design time (see <Timing
**         dialog box> - Runtime setting - from a list of values).
**         Each of these settings constitutes a mode and Processor
**         Expert^[TM] assigns them a mode identifier. The prescaler
**         and compare values corresponding to each mode are
**         calculated at design time. You may switch modes at
**         runtime by referring only to a mode identifier. No
**         run-time calculations are performed, all the calculations
**         are performed at design time.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Mod             - Timing mode to set
**                           List of timing mode symbols 
**                           defined in SDSerial.h:
**                           0   SDSerial_BM_2_666667US 2_666667us
**                           1   SDSerial_BM_0_083333US 0_083333us
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SDSerial_SetBaudRateMode(byte Mod)
{
  static const  byte SDSerial_BaudRate[2] = {5,0};

  if (Mod >= 2U) {
    return ERR_VALUE;
  }
  SPI2BR = SDSerial_BaudRate[Mod];
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  SDSerial_GetError (component SynchroMaster)
**     Description :
**         Returns a set of errors on the channel (errors that cannot
**         be returned in given methods). The component accumulates
**         errors in a set; after calling [GetError] this set is
**         returned and cleared. This method is available only if the
**         "Interrupt service/event" property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - A pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SDSerial_GetError(SDSerial_TError *Err)
{
  EnterCritical();                     /* Save the PS register */
  Err->err = 0x00U;
  Err->errName.OverRun = ((ErrFlag & OVERRUN_ERR) ? 1U : 0U); /* Overrun error */
  ErrFlag = 0x00U;                     /* Reset error flags */
  ExitCritical();                      /* Restore the PS register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SDSerial_Interrupt (component SynchroMaster)
**
**     Description :
**         The method services the error interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR       0x01U
#define ON_FULL_RX     0x02U
#define ON_RX_CHAR     0x04U
#define ON_FREE_TX     0x08U
#define ON_TX_CHAR     0x10U
#define ON_RX_CHAR_EXT 0x20U
ISR(SDSerial_Interrupt)
{
  SDSerial_TComData Data = 0U;         /* Temporary variable for data */
  byte Flags = 0U;                     /* Temporary variable for flags */
  byte Status;                         /* Temporary variable for flags */

  Status = SPI2S;                      /* Read the device error register */
  Data = SPI2DL;                       /* Read data from receiver */
  if (SerFlag & CHAR_IN_RX) {          /* Is the overrun error flag set? */
    SerFlag |= OVERRUN_ERR;            /* If yes then set the Overrun error flag */
    Flags |= ON_ERROR;                 /* If yes then set the OnError flag */
  }
  SerFlag |= CHAR_IN_RX;               /* Set flag "char in RX buffer" */
  BufferRead = Data;                   /* Read data from receiver */
  Flags |= ON_RX_CHAR;                 /* Set the OnRxChar flag */
  ErrFlag |= SerFlag;                  /* Update error flag mirror */
  SerFlag &= (byte)(~(byte)FULL_TX);   /* Reset flag "full TX buffer" */

  if (Flags & ON_ERROR) {              /* Is the error flag set? */
    SDSerial_OnError();                /* If yes then invoke user event */
  } else {
    if (Flags & ON_RX_CHAR) {          /* Is OnRxChar flag set? */
      SDSerial_OnRxChar();             /* If yes then invoke user event */
    }
  }
  SDSerial_OnTxChar();                 /* If yes then invoke user event */
}

/*
** ===================================================================
**     Method      :  SDSerial_Init (component SynchroMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SDSerial_Init(void)
{
  SerFlag = 0U;                        /* Reset all flags */
  ErrFlag = 0U;                        /* Reset all flags in mirror */
  EnUser = FALSE;                      /* Disable device */
  #pragma MESSAGE DISABLE C4002        /* Disable warning C4002 "Result not used" */
  (void)SPI2S;                         /* Read the status register */
  (void)SPI2DL;                        /* Read the data register */
  /* SPI2BR: ??=0,SPPR2=0,SPPR1=0,SPPR0=0,??=0,SPR2=1,SPR1=0,SPR0=1 */
  setReg8(SPI2BR, 0x05U);              /* Set the baud rate register */ 
  /* SPI2C2: SPMIE=0,SPIMODE=0,??=0,MODFEN=0,BIDIROE=0,??=0,SPISWAI=0,SPC0=0 */
  setReg8(SPI2C2, 0x00U);              /* Configure the SPI port - control register 2 */ 
  /* SPI2C1: SPIE=0,SPE=0,SPTIE=0,MSTR=1,CPOL=0,CPHA=1,SSOE=0,LSBFE=1 */
  setReg8(SPI2C1, 0x15U);              /* Configure the SPI port - control register 1 */ 
  HWEnDi();                            /* Enable/disable device according to the status flags */
}


/* END SDSerial. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
